services:
  dev:
    container_name: template-go-console-app-dev
    build:
      context: ./
      dockerfile: Dockerfile
      target: dev
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    volumes:
      - ".:/template-go-console-app"
      - "./zshrc:/home/dev/.zshrc"
      - template-go-console-app-cache:/cache
      - /var/run/docker.sock:/var/run/docker.sock
      - template-go-console-app-gocache:/home/dev/.cache/go-build
      - template-go-console-app-gomod:/home/dev/go/pkg/mod
    environment:
      - GOPATH=/home/dev/go
      - GOCACHE=/home/dev/.cache/go-build
      - HISTFILE=/cache/.zsh_history
    entrypoint: top -b
    logging:
      driver: none

volumes:
  template-go-console-app-cache:
  template-go-console-app-gocache:
  template-go-console-app-gomod:
